/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    [keys: string]: THREE.Mesh
  }
  materials: {
    [keys: string]: THREE.MeshStandardMaterial
  }
}

const AvatarBoots = ({ ...props }: JSX.IntrinsicElements["group"]) => {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF("/char/avatar_clothes/clothes.glb") as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      {/* boots */}
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.F_PRD_21FW_SH002_1.geometry} material={materials.NewMat10} castShadow />
        <mesh geometry={nodes.F_PRD_21FW_SH002_2.geometry} material={materials.NewMat10} castShadow />
        <mesh geometry={nodes.F_PRD_21FW_SH002_3.geometry} material={materials.NewMat10} castShadow />
      </group>
    </group>
  )
}

useGLTF.preload("/char/avatar_clothes/clothes.glb")

export default AvatarBoots
