/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    F_FOOT_1: THREE.Mesh
    F_Body_1: THREE.Mesh
    F_Body_2: THREE.Mesh
    F_Body_3: THREE.Mesh
    F_Body_4: THREE.Mesh
    F_Body_5: THREE.Mesh
    F_Body_6: THREE.Mesh
    F_Body_7: THREE.Mesh
    F_Body_8: THREE.Mesh
    F_Body_9: THREE.Mesh
    F_Body_10: THREE.Mesh
    F_Body_11: THREE.Mesh
    F_Body_12: THREE.Mesh
    F_Body_13: THREE.Mesh
    F_Body_14: THREE.Mesh
    F_Body_15: THREE.Mesh
    F_Body_16: THREE.Mesh
    F_Body_17: THREE.Mesh
    F_Body_18: THREE.Mesh
    F_Body_19: THREE.Mesh
    F_Body_20: THREE.Mesh
    F_Body_21: THREE.Mesh
    F_Body_22: THREE.Mesh
    F_Body_23: THREE.Mesh
    F_Body_24: THREE.Mesh
    F_Body_25: THREE.Mesh
    F_Body_26: THREE.Mesh
    F_Body_27: THREE.Mesh
    F_Body_28: THREE.Mesh
    F_Body_29: THREE.Mesh
    F_Body_30: THREE.Mesh
    F_Body_31: THREE.Mesh
    F_Body_32: THREE.Mesh
    F_Body_33: THREE.Mesh
    F_Body_34: THREE.Mesh
    F_Body_35: THREE.Mesh
    F_Body_36: THREE.Mesh
    F_Body_37: THREE.Mesh
    F_Body_38: THREE.Mesh
    F_Body_39: THREE.Mesh
    F_Body_40: THREE.Mesh
    F_Body_41: THREE.Mesh
    F_Body_42: THREE.Mesh
    F_Body_43: THREE.Mesh
    F_Body_44: THREE.Mesh
    F_Body_45: THREE.Mesh
    F_Body_46: THREE.Mesh
    F_Body_47: THREE.Mesh
    F_Body_48: THREE.Mesh
    F_Body_49: THREE.Mesh
    F_Body_50: THREE.Mesh
    F_Body_51: THREE.Mesh
    F_Body_52: THREE.Mesh
    F_Body_53: THREE.Mesh
    F_Body_54: THREE.Mesh
    F_Body_55: THREE.Mesh
    F_Body_56: THREE.Mesh
    F_Body_57: THREE.Mesh
    F_Body_58: THREE.Mesh
    F_Body_59: THREE.Mesh
    F_Body_60: THREE.Mesh
    F_Body_61: THREE.Mesh
    F_Whiteface_002_eye: THREE.Mesh
    F_Whiteface_002_1: THREE.Mesh
    F_Whiteface_002_2: THREE.Mesh
    F_Whiteface_002_3: THREE.Mesh
    F_Whiteface_002_4: THREE.Mesh
    F_Whiteface_002_5: THREE.Mesh
    F_HAIR_1030000: THREE.Mesh
    F_AREA_21SS_D004_1: THREE.Mesh
    F_AREA_21SS_D004_2: THREE.Mesh
    F_AREA_21SS_D004_3: THREE.Mesh
    F_AREA_21SS_D004_4: THREE.Mesh
    F_AREA_21SS_D004_5: THREE.Mesh
    F_AREA_21SS_D004_6: THREE.Mesh
    F_PRD_21FW_SH002_1: THREE.Mesh
    F_PRD_21FW_SH002_2: THREE.Mesh
    F_PRD_21FW_SH002_3: THREE.Mesh
  }
  materials: {
    NewMat01: THREE.MeshStandardMaterial
    NewMat08: THREE.MeshStandardMaterial
    NewMat02: THREE.MeshStandardMaterial
    teeth: THREE.MeshStandardMaterial
    NewMat05: THREE.MeshStandardMaterial
    NewMat07: THREE.MeshStandardMaterial
    NewMat06: THREE.MeshStandardMaterial
    NewMat03: THREE.MeshStandardMaterial
    NewMat09: THREE.MeshStandardMaterial
    NewMat10: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/clothes.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.F_FOOT_1.geometry} material={materials.NewMat01} rotation={[-Math.PI / 2, 0, 0]} />
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.F_Body_1.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_2.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_3.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_4.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_5.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_6.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_7.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_8.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_9.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_10.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_11.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_12.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_13.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_14.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_15.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_16.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_17.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_18.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_19.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_20.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_21.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_22.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_23.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_24.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_25.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_26.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_27.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_28.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_29.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_30.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_31.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_32.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_33.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_34.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_35.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_36.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_37.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_38.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_39.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_40.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_41.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_42.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_43.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_44.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_45.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_46.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_47.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_48.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_49.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_50.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_51.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_52.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_53.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_54.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_55.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_56.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_57.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_58.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_59.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_60.geometry} material={materials.NewMat01} />
        <mesh geometry={nodes.F_Body_61.geometry} material={materials.NewMat01} />
      </group>
      <mesh geometry={nodes.F_Whiteface_002_eye.geometry} material={materials.NewMat08} rotation={[-Math.PI / 2, 0, 0]} />
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.F_Whiteface_002_1.geometry} material={materials.NewMat02} />
        <mesh geometry={nodes.F_Whiteface_002_2.geometry} material={materials.teeth} />
        <mesh geometry={nodes.F_Whiteface_002_3.geometry} material={materials.NewMat05} />
        <mesh geometry={nodes.F_Whiteface_002_4.geometry} material={materials.NewMat07} />
        <mesh geometry={nodes.F_Whiteface_002_5.geometry} material={materials.NewMat06} />
      </group>
      <mesh geometry={nodes.F_HAIR_1030000.geometry} material={materials.NewMat03} rotation={[-Math.PI / 2, 0, 0]} />
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.F_AREA_21SS_D004_1.geometry} material={materials.NewMat09} />
        <mesh geometry={nodes.F_AREA_21SS_D004_2.geometry} material={materials.NewMat09} />
        <mesh geometry={nodes.F_AREA_21SS_D004_3.geometry} material={materials.NewMat09} />
        <mesh geometry={nodes.F_AREA_21SS_D004_4.geometry} material={materials.NewMat09} />
        <mesh geometry={nodes.F_AREA_21SS_D004_5.geometry} material={materials.NewMat09} />
        <mesh geometry={nodes.F_AREA_21SS_D004_6.geometry} material={materials.NewMat09} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.F_PRD_21FW_SH002_1.geometry} material={materials.NewMat10} />
        <mesh geometry={nodes.F_PRD_21FW_SH002_2.geometry} material={materials.NewMat10} />
        <mesh geometry={nodes.F_PRD_21FW_SH002_3.geometry} material={materials.NewMat10} />
      </group>
    </group>
  )
}

useGLTF.preload('/clothes.glb')
