/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Smithsonian Institution (https://sketchfab.com/Smithsonian)
license: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
source: https://sketchfab.com/3d-models/baluster-vase-one-of-three-in-a-five-piece-50bbce380bff46c491ed9887e278f690
title: Baluster Vase, One of Three in a Five-Piece
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    ['ml.001']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.material} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.material} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials['ml.001']} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials['ml.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
