/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    [keys: string]: THREE.Mesh
  }
  materials: {
    [keys: string]: THREE.MeshStandardMaterial
  }
}

export default function Body({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF(
    "char/haus/NFT_BOOTS_OP1.glb"
  ) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      {/* 옆면 */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OP1_BASE_01.geometry}
        material={materials.NFT_BOOTS_OP1}
        rotation={[-Math.PI / 2, 0, 0]}
        material-color="red"
      />
      {/* 앞면 */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OP1_BASE_02.geometry}
        material={materials.NFT_BOOTS_OP1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/* 신발끈 */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OP1_BASE_03.geometry}
        material={materials.NFT_BOOTS_OP1}
        rotation={[-Math.PI / 2, 0, 0]}
        material-color="white"
      />
      {/* 발목 뒤 */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OP1_BASE_04.geometry}
        material={materials.NFT_BOOTS_OP1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/* 뒷 꼬랑지 */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OP1_BASE_05.geometry}
        material={materials.NFT_BOOTS_OP1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload("char/haus/NFT_BOOTS_OP1.glb")
