/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF("/assets/test.glb") as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10"].geometry}
        material={materials["Glass 1 (1)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["042"].geometry}
        material={materials["Material #2348021"]}
        position={[-76.41, 14.31, 193.81]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856210.geometry}
        material={materials["Material #2348010"]}
        position={[-62.05, 14.32, 224.4]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856211.geometry}
        material={materials.Tire}
        position={[-62.08, 14.32, 224.46]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["043"].geometry}
        material={materials["Material #2348032"]}
        position={[-76.41, 14.31, 193.81]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["044"].geometry}
        material={materials["Material #2347997"]}
        position={[-55.14, 14.34, 238.99]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_or003"].geometry}
        material={materials.Default}
        position={[-76.41, 14.31, 193.81]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group67300.geometry}
        material={materials["Material #2348005"]}
        position={[-68.38, 14.28, 226.43]}
        rotation={[-1.57, -0.01, 0.44]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856209.geometry}
        material={materials["Material #2347996"]}
        position={[-62.41, 14.34, 223.9]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={[-1.07, 1.07, 1.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube036.geometry}
        material={materials["Material #2348021"]}
        position={[-62.47, 14.32, 223.81]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={[-1.07, 1.07, 1.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group67302.geometry}
        material={materials["Material #2347998"]}
        position={[-62.3, 14.22, 223.45]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={[-1.07, 1.07, 1.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["039"].geometry}
        material={materials["Material #2347996"]}
        position={[-47.99, 14.31, 186.71]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={[-1.01, 1.01, 1.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["040"].geometry}
        material={materials["Material #2348032"]}
        position={[-47.99, 14.31, 186.71]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={[-1.01, 1.01, 1.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856206.geometry}
        material={materials["Material #2348010"]}
        position={[-62.35, 14.32, 156.12]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856207.geometry}
        material={materials.Tire}
        position={[-62.32, 14.32, 156.06]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["041"].geometry}
        material={materials["Material #2347997"]}
        position={[-69.26, 14.34, 141.53]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_or002"].geometry}
        material={materials["Material #2348049"]}
        position={[-47.99, 14.31, 186.71]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={[-1.01, 1.01, 1.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube035.geometry}
        material={materials["Material #2348021"]}
        position={[-62.07, 14.32, 156.78]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={1.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group67298.geometry}
        material={materials["Material #2348005"]}
        position={[-67.88, 14.28, 159.62]}
        rotation={[-1.57, -0.01, -2.71]}
        scale={[-0.97, 0.97, 0.97]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856208.geometry}
        material={materials["Material #2347996"]}
        position={[-62.11, 14.34, 156.67]}
        rotation={[-Math.PI / 2, 0, -2.71]}
        scale={1.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group67299.geometry}
        material={materials["Material #2347998"]}
        position={[-61.69, 14.22, 156.88]}
        rotation={[-Math.PI / 2, 0, 0.44]}
        scale={1.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object226689.geometry}
        material={materials["Material #2348010"]}
        position={[57.98, 14.32, 223.33]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object226688.geometry}
        material={materials.Tire}
        position={[57.93, 14.32, 223.38]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4"].geometry}
        material={materials["Material #2348021"]}
        position={[57.89, 14.31, 189.54]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["6"].geometry}
        material={materials["Material #2348032"]}
        position={[57.89, 14.31, 189.54]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["5"].geometry}
        material={materials["Material #2347997"]}
        position={[58.08, 14.34, 239.48]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_or"].geometry}
        material={materials.Default}
        position={[57.89, 14.31, 189.54]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856046.geometry}
        material={materials["Material #2347996"]}
        position={[57.87, 14.34, 222.74]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.07, 1.07, 1.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube033.geometry}
        material={materials["Material #2348021"]}
        position={[57.85, 14.32, 222.62]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.07, 1.07, 1.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group67288.geometry}
        material={materials["Material #2347998"]}
        position={[58.16, 14.22, 222.37]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-1.07, 1.07, 1.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group67291.geometry}
        material={materials["Material #2348005"]}
        position={[51.39, 14.28, 222.5]}
        rotation={[-Math.PI / 2, -0.01, 0]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["036"].geometry}
        material={materials["Material #2348032"]}
        position={[57.97, 14.31, 191.66]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-1.01, 1.01, 1.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856203.geometry}
        material={materials["Material #2348010"]}
        position={[57.88, 14.32, 157.87]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856204.geometry}
        material={materials.Tire}
        position={[57.93, 14.32, 157.82]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["037"].geometry}
        material={materials["Material #2347996"]}
        position={[57.97, 14.31, 191.66]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-1.01, 1.01, 1.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["038"].geometry}
        material={materials["Material #2347997"]}
        position={[57.79, 14.34, 141.72]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_or001"].geometry}
        material={materials["Material #2348049"]}
        position={[57.97, 14.31, 191.66]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-1.01, 1.01, 1.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group67293.geometry}
        material={materials["Material #2348005"]}
        position={[51.39, 14.28, 158.7]}
        rotation={[-Math.PI / 2, -0.01, Math.PI]}
        scale={[-0.97, 0.97, 0.97]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856205.geometry}
        material={materials["Material #2347996"]}
        position={[57.87, 14.34, 158.46]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={1.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube034.geometry}
        material={materials["Material #2348021"]}
        position={[57.85, 14.32, 158.58]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={1.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group67295.geometry}
        material={materials["Material #2347998"]}
        position={[58.16, 14.22, 158.83]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4_1"].geometry}
        material={materials["Material #2348037"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["6_1"].geometry}
        material={materials["Material #2348039"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2"].geometry}
        material={materials["Material #2348059"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1"].geometry}
        material={materials["1 (1)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_gray"].geometry}
        material={materials["Material #2348039 (2)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856184.geometry}
        material={materials.BLACK}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856473.geometry}
        material={materials["Material #2348058"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder136.geometry}
        material={materials["Material #2348034"]}
        position={[59.18, 57.66, 167.01]}
        rotation={[1.57, 1.21, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder137.geometry}
        material={materials["Material #2347997"]}
        position={[67.07, 54.74, 167.46]}
        rotation={[1.57, 1.21, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856469.geometry}
        material={materials.Default}
        position={[9.03, 29.06, 155.01]}
        rotation={[-Math.PI / 2, 0, -2.01]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856470.geometry}
        material={materials.Default}
        position={[9.62, 32.84, 155.16]}
        rotation={[-Math.PI / 2, 0, 2.62]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856471.geometry}
        material={materials.Default}
        position={[9.84, 37.46, 154.59]}
        rotation={[-Math.PI / 2, 0, -1.69]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["048"].geometry}
        material={materials.Default}
        position={[-39.46, 28.41, 154.68]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1855258.geometry}
        material={materials.Default}
        position={[9.03, 29.06, 226.19]}
        rotation={[-Math.PI / 2, 0, -1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1855256.geometry}
        material={materials.Default}
        position={[9.62, 32.84, 226.04]}
        rotation={[-Math.PI / 2, 0, Math.PI / 6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1855257.geometry}
        material={materials.Default}
        position={[9.84, 37.46, 226.61]}
        rotation={[-Math.PI / 2, 0, -1.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["0"].geometry}
        material={materials.Default}
        position={[-39.46, 28.41, 226.52]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder134.geometry}
        material={materials["Material #2348034"]}
        position={[59.18, 57.66, 214.19]}
        rotation={[1.57, 1.21, 3.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder135.geometry}
        material={materials["Material #2347997"]}
        position={[67.07, 54.74, 213.74]}
        rotation={[1.57, 1.21, 3.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856464.geometry}
        material={materials["Material #2348006"]}
        position={[96.65, 26.14, 190.6]}
        rotation={[-Math.PI / 2, -0.07, Math.PI]}
        scale={1.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["!Rectangle026"].geometry}
        material={materials["Material #2348005"]}
        position={[96.24, 26.07, 190.6]}
        rotation={[-Math.PI / 2, -0.07, Math.PI]}
        scale={1.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856463.geometry}
        material={materials["Material #2348053"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856456.geometry}
        material={materials["Material #2348044"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856454.geometry}
        material={materials["Material #2348051"]}
        position={[-0.04, 0.14, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856452.geometry}
        material={materials["Material #2348005"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856201.geometry}
        material={materials["Material #2348039 (1)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856200.geometry}
        material={materials["Material #2348044"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856198.geometry}
        material={materials["Material #2348039"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856197.geometry}
        material={materials["Material #2348038 (1)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object003.geometry}
        material={materials["Material #2348040"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10_1"].geometry}
        material={materials["Material #2348050"]}
        position={[74.09, 50.73, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["5_1"].geometry}
        material={materials["Material #2348038"]}
        position={[94.67, 42.02, 190.94]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2_1"].geometry}
        material={materials.BLACK}
        position={[76.03, 44.97, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_74.geometry}
        material={materials["Material #2348034"]}
        position={[95.26, 30.58, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["0000"].geometry}
        material={materials.Default}
        position={[51.71, 60.13, 190.6]}
        rotation={[-Math.PI / 2, 0.26, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1_1"].geometry}
        material={materials["Material #2348016"]}
        position={[-27.91, 46.31, 190.6]}
        rotation={[-Math.PI / 2, 0.69, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_red_g"].geometry}
        material={materials["Material #2348036"]}
        position={[91.91, 41.59, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4_2"].geometry}
        material={materials["Material #2347996"]}
        position={[91.33, 41.52, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_rel_2"].geometry}
        material={materials["Material #2348039"]}
        position={[91.54, 41.64, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["8"].geometry}
        material={materials["Material #2348044"]}
        position={[90.49, 42.32, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_red_l"].geometry}
        material={materials["Material #2348040"]}
        position={[92.99, 41.62, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3"].geometry}
        material={materials["Material #2348062"]}
        position={[93.86, 36.58, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["6_2"].geometry}
        material={materials["Material #2347998"]}
        position={[94.81, 30.58, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_rel"].geometry}
        material={materials["Material #2348046"]}
        position={[90.67, 41.84, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856068.geometry}
        material={materials["Material #2348005"]}
        position={[-29.08, 54.1, 190.6]}
        rotation={[-Math.PI / 2, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856453.geometry}
        material={materials["Glass 1"]}
        position={[74.09, 50.73, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856459.geometry}
        material={materials["Material #2348052"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10_2"].geometry}
        material={materials["Glass 1 (1) (1)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856195.geometry}
        material={materials["Material #2348050"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2_2"].geometry}
        material={materials["Material #2348034"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["6_3"].geometry}
        material={materials["Material #2347998"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_red_g_1"].geometry}
        material={materials["Glass 1 (2)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_rel_5"].geometry}
        material={materials["Material #2348054"]}
        position={[0.03, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["9"].geometry}
        material={materials.NewMat02}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["8_1"].geometry}
        material={materials.NewMat02}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_rel_3"].geometry}
        material={materials["Material #2348046"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_l"].geometry}
        material={materials["Material #2348039 (1)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_rel_1"].geometry}
        material={materials["Material #2348046"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_or_l"].geometry}
        material={materials["Material #2348040"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1_2"].geometry}
        material={materials.Default}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_yellow"].geometry}
        material={materials["Material #2348043"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_"].geometry}
        material={materials["Material #29"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_speed"].geometry}
        material={materials["Material #2348057"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12"].geometry}
        material={materials["Material #2348059"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_red"].geometry}
        material={materials["Material #2348056"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_rel_6"].geometry}
        material={materials["Material #2348046"]}
        position={[87.99, 41.78, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["9_1"].geometry}
        material={materials["Material #2348039"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_yellow_1"].geometry}
        material={materials["Material #2348043"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["6_4"].geometry}
        material={materials["Material #2348039"]}
        position={[-16.66, 16.9, 227.72]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1_3"].geometry}
        material={materials["1 (1)"]}
        position={[-18.49, 28.54, 226.59]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2_3"].geometry}
        material={materials["Material #2348059"]}
        position={[-15.41, 36.65, 225.97]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_mirror"].geometry}
        material={materials.Mirror}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["9_2"].geometry}
        material={materials["Material #2348039"]}
        position={[-28.04, 44.86, 234.06]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_or_l_1"].geometry}
        material={materials["Material #2348032"]}
        position={[-28.07, 44.86, 233.99]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10_3"].geometry}
        material={materials["Glass 1 (1) (1)"]}
        position={[-11.47, 52.92, 221.09]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2_4"].geometry}
        material={materials["Material #2348034"]}
        position={[-18.16, 31.94, 224.22]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4_3"].geometry}
        material={materials["Material #2348038 (1) (1)"]}
        position={[-11.54, 53.44, 226.16]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["6_5"].geometry}
        material={materials["Material #2347998"]}
        position={[-13.91, 36.97, 222.55]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["8_2"].geometry}
        material={materials["Material #2348055"]}
        position={[-30.8, 21.85, 220.57]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856479.geometry}
        material={materials["Material #2348063"]}
        position={[-58.85, 0, 174.6]}
        rotation={[-Math.PI / 2, 0, 1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856477.geometry}
        material={materials["Material #2348062"]}
        position={[-58.85, 0, 174.6]}
        rotation={[-Math.PI / 2, 0, 1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856475.geometry}
        material={materials["Material #2348061"]}
        position={[-58.85, 0, 174.6]}
        rotation={[-Math.PI / 2, 0, 1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object15.geometry}
        material={materials["Material #2348068"]}
        position={[-22.69, 31.91, 221.67]}
        rotation={[-Math.PI / 2, 0, -0.04]}
        scale={[0.84, 0.84, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["5_2"].geometry}
        material={materials["Material #2348038"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["026"].geometry}
        material={materials["Material #2347998"]}
        position={[29.33, 39.38, 158.76]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["027"].geometry}
        material={materials["Glass 1"]}
        position={[26.95, 53.97, 160.37]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["028"].geometry}
        material={materials["Material #2348034"]}
        position={[27.24, 32.03, 156.96]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["029"].geometry}
        material={materials["Material #2348016"]}
        position={[26.2, 31.11, 155.04]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["033"].geometry}
        material={materials["Material #2348055"]}
        position={[16.07, 30.21, 160]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856188.geometry}
        material={materials["Material #2348034"]}
        position={[25.39, 36.78, 158.9]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856190.geometry}
        material={materials["Material #2348037"]}
        position={[17.91, 18.48, 153.42]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856186.geometry}
        material={materials["Material #2347996"]}
        position={[26.97, 53.89, 160.34]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856480.geometry}
        material={materials["Material #2348063"]}
        position={[-31.22, 0, 164.65]}
        rotation={[-Math.PI / 2, 0, -1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group9.geometry}
        material={materials["Material #2348062"]}
        position={[-31.22, 0, 164.65]}
        rotation={[-Math.PI / 2, 0, -1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group8.geometry}
        material={materials["Material #2348061"]}
        position={[-31.22, 0, 164.65]}
        rotation={[-Math.PI / 2, 0, -1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object18.geometry}
        material={materials["Material #2348068"]}
        position={[23.58, 34.12, 159.86]}
        rotation={[-1.57, -0.27, -0.01]}
        scale={[1, 1, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856191.geometry}
        material={materials["Material #2348033"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10_4"].geometry}
        material={materials["Glass 1 (1) (1)"]}
        position={[26.95, 53.97, 220.83]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2_5"].geometry}
        material={materials["Material #2348034"]}
        position={[27.24, 32.03, 224.24]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1_4"].geometry}
        material={materials["1 (1)"]}
        position={[26.2, 31.11, 226.16]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["6_6"].geometry}
        material={materials["Material #2348039"]}
        position={[17.91, 18.48, 227.78]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2_6"].geometry}
        material={materials["Material #2348059"]}
        position={[25.39, 36.78, 222.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["6_7"].geometry}
        material={materials["Material #2347998"]}
        position={[29.33, 39.38, 222.44]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["8_3"].geometry}
        material={materials["Material #2348055"]}
        position={[16.07, 30.21, 221.2]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4_4"].geometry}
        material={materials["Material #2348038 (1) (1)"]}
        position={[26.97, 53.89, 220.86]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856482.geometry}
        material={materials["Material #2348063"]}
        position={[-31.22, 0, 216.55]}
        rotation={[-Math.PI / 2, 0, 1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856476.geometry}
        material={materials["Material #2348062"]}
        position={[-31.22, 0, 216.55]}
        rotation={[-Math.PI / 2, 0, 1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856474.geometry}
        material={materials["Material #2348061"]}
        position={[-31.22, 0, 216.55]}
        rotation={[-Math.PI / 2, 0, 1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object17.geometry}
        material={materials["Material #2348068"]}
        position={[23.56, 34.13, 221.37]}
        rotation={[-1.53, -0.29, 0]}
        scale={[1, 1, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4_5"].geometry}
        material={materials["Material #2347996"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_1"].geometry}
        material={materials["Material #2348060"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_mirror_1"].geometry}
        material={materials["Material #2348048"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_or_l001"].geometry}
        material={materials["Material #2348032"]}
        position={[-28.07, 44.86, 147.21]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["016"].geometry}
        material={materials["1 (1)"]}
        position={[-18.49, 28.54, 154.61]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["019"].geometry}
        material={materials["Glass 1"]}
        position={[-11.47, 52.92, 160.11]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["020"].geometry}
        material={materials["Material #2348034"]}
        position={[-18.16, 31.94, 156.77]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["023"].geometry}
        material={materials["Material #2347998"]}
        position={[-13.91, 37.02, 158.38]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["024"].geometry}
        material={materials["Material #2348055"]}
        position={[-30.8, 21.85, 160.63]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856185.geometry}
        material={materials["Material #2347996"]}
        position={[-11.54, 53.44, 155.04]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856187.geometry}
        material={materials["Material #2348037"]}
        position={[-16.66, 16.9, 153.48]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856189.geometry}
        material={materials["Material #2348034"]}
        position={[-15.41, 36.65, 155.23]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856202.geometry}
        material={materials["Material #2348039"]}
        position={[-28.04, 44.86, 147.14]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856481.geometry}
        material={materials["Material #2348063"]}
        position={[-58.85, 0, 206.6]}
        rotation={[-Math.PI / 2, 0, -1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group14.geometry}
        material={materials["Material #2348061"]}
        position={[-58.85, 0, 206.6]}
        rotation={[-Math.PI / 2, 0, -1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group13.geometry}
        material={materials["Material #2348062"]}
        position={[-58.85, 0, 206.6]}
        rotation={[-Math.PI / 2, 0, -1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856483.geometry}
        material={materials["Material #2348048"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object16.geometry}
        material={materials["Material #2348068"]}
        position={[-21.08, 31.74, 159.58]}
        rotation={[-1.58, -0.19, -0.1]}
        scale={[1, 1, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856194.geometry}
        material={materials["Glass 1 (1)"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856472.geometry}
        material={materials.BLACK}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["7"].geometry}
        material={materials["Material #2348032"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1855971.geometry}
        material={materials.Default}
        position={[-98.71, 21.75, 190.6]}
        rotation={[-Math.PI / 2, -0.1, 0]}
        scale={1.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["!Rectangle025"].geometry}
        material={materials["1 (1)"]}
        position={[-98.3, 21.75, 190.6]}
        rotation={[-Math.PI / 2, -0.1, 0]}
        scale={1.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group1.geometry}
        material={materials["Material #2348066"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group2.geometry}
        material={materials["Material #2348065"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group3.geometry}
        material={materials["Material #2348062"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group4.geometry}
        material={materials["Material #2348061"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group10.geometry}
        material={materials["Material #2348064"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group11.geometry}
        material={materials["Material #2348067"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856478.geometry}
        material={materials["Material #2348046"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group006.geometry}
        material={materials["Material #2348063"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_red_l001"].geometry}
        material={materials["Material #2348040"]}
        position={[0, -0.71, 190.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["12_red_g001"].geometry}
        material={materials["Material #2348052"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856484.geometry}
        material={materials["Material #2348034"]}
        position={[-27.3, 38.01, 200.8]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.w.geometry}
        material={materials["Material #2348068"]}
        position={[-23.62, 32.49, 203.64]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.84}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856485.geometry}
        material={materials["Material #2348065"]}
        position={[0, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856198_1.geometry}
        material={materials["Material #49"]}
        position={[-0.96, 0, 190.6]}
        rotation={[-1.57, 0, 0]}
        scale={0.99}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ellipse002.geometry}
        material={materials.NewMat01}
        position={[-96.87, 32.13, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.39}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856199.geometry}
        material={materials.BLACK}
        position={[-0.96, 0, 190.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.39}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object1856199_1.geometry}
        material={materials["Material #2348039"]}
        position={[-0.8, 0, 190.6]}
        rotation={[-1.57, 0, 0]}
        scale={0.99}
      />
    </group>
  )
}

useGLTF.preload("/assets/test.glb")
