/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_0_1: THREE.Mesh
    mesh_0_2: THREE.Mesh
    mesh_0_3: THREE.Mesh
    mesh_0_4: THREE.Mesh
    mesh_0_5: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_1_1: THREE.Mesh
    mesh_1_2: THREE.Mesh
  }
  materials: {
    char_astrella_eyelashes_mat: THREE.MeshStandardMaterial
    char_astrella_eyes_mat: THREE.MeshStandardMaterial
    char_astrella_suit_mat: THREE.MeshStandardMaterial
    char_astrella_skin_mat: THREE.MeshStandardMaterial
    char_astrella_plastic_mat: THREE.MeshStandardMaterial
    char_astrella_metal_mat: THREE.MeshStandardMaterial
    char_astrella_glass_mat: THREE.MeshStandardMaterial
  }
}

interface Props {
  props?: JSX.IntrinsicElements['group']
  color: string
}

export default function TestCharacter({ color, ...props }: Props) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/glb/char_astrella.glb') as GLTFResult
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.025}
      castShadow
      receiveShadow
    >
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={materials.char_astrella_eyelashes_mat}
        material-color={color}
      />
      <mesh
        geometry={nodes.mesh_0_1.geometry}
        material={materials.char_astrella_eyes_mat}
        material-color={color}
      />
      <mesh
        geometry={nodes.mesh_0_2.geometry}
        material={materials.char_astrella_metal_mat}
        material-color={color}
      />
      <mesh
        geometry={nodes.mesh_0_3.geometry}
        material={materials.char_astrella_plastic_mat}
        material-color={color}
      />
      <mesh
        geometry={nodes.mesh_0_4.geometry}
        material={materials.char_astrella_suit_mat}
        material-color={color}
      />
      <mesh
        geometry={nodes.mesh_0_5.geometry}
        material={materials.char_astrella_skin_mat}
        material-color={color}
      />
      <mesh
        geometry={nodes.mesh_1.geometry}
        material={materials.char_astrella_plastic_mat}
        material-color={color}
      />
      <mesh
        geometry={nodes.mesh_1_1.geometry}
        material={materials.char_astrella_metal_mat}
        material-color={color}
      />
      <mesh
        geometry={nodes.mesh_1_2.geometry}
        material={materials.char_astrella_glass_mat}
        material-color={color}
      />
    </group>
  )
}

useGLTF.preload('/glb/char_astrella.glb')
