/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    [keys: string]: THREE.Mesh
  }
  materials: {
    [keys: string]: THREE.MeshStandardMaterial
  }
}

const TestBoots = ({ ...props }: JSX.IntrinsicElements["group"] | any) => {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF("/char/avatar_clothes/clothes.glb") as GLTFResult

  console.log("props.texture.current", props.texture.current)

  const myMaterial = new THREE.MeshPhysicalMaterial()
  myMaterial.map = new THREE.CanvasTexture(props.texture.current)

  return (
    <group ref={group} {...props} dispose={null}>
      {/* boots */}
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.F_PRD_21FW_SH002_1.geometry} material={myMaterial} castShadow />
        <mesh geometry={nodes.F_PRD_21FW_SH002_2.geometry} material={materials.NewMat10} castShadow />
        <mesh geometry={nodes.F_PRD_21FW_SH002_3.geometry} material={materials.NewMat10} castShadow />
      </group>
    </group>
  )
}

useGLTF.preload("/char/avatar_clothes/clothes.glb")

export default TestBoots
